#!/usr/bin/perl

use strict;
use warnings;

# Stream url from radiocroco.info
my $stream_url = 'https://radiocroco.info/streaming/radiocroco_64.mp3';

print "Streaming from $stream_url\n";

exec('gst-launch', '--quiet', 'playbin', "uri=$stream_url");
